name: Deploy to cPanel

on:
  push:
    branches:
      - master  # Adjust to your default branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DIPENDRA }}

      - name: Deploy to cPanel
        run: |
          ssh dipendr5@dipendratamang.com.np 'source /home/dipendr5/virtualenv/python/3.8/bin/activate && cd /home/dipendr5/python/djangopersonalsite && git pull origin master && pip install -r requirements.txt && python manage.py migrate'
