name: Deploy to cPanel

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Deploy to cPanel
        env:
          CPANEL_USER: ${{ secrets.CPANEL_USER }}
          CPANEL_HOST: ${{ secrets.CPANEL_HOST }}
          CPANEL_PORT: ${{ secrets.CPANEL_PORT }}
        run: |
          ssh $CPANEL_USER@$CPANEL_HOST -p $CPANEL_PORT << 'EOF'
          cd /home/username/django_project
          source /home/username/python_app/venv/bin/activate
          git pull origin main
          pip install -r requirements.txt
          python manage.py migrate
          python manage.py collectstatic --noinput
          touch /home/username/django_project/tmp/restart.txt
          EOF
