name: Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Deploy to cPanel
        env:
          CPANEL_USER: dipendr5  # Replace with your cPanel username
          CPANEL_HOST: python.dipendratamang.com.np  # Replace with your cPanel host/domain/IP
          CPANEL_PORT: 2222  # Replace with your cPanel SSH port
        run: |
          ssh $CPANEL_USER@$CPANEL_HOST -p $CPANEL_PORT << 'EOF'
          cd /home/dipendr5/django_project  # Adjust path as per your project structure
          source /home/dipendr5/python_app/venv/bin/activate
          git pull origin main
          pip install -r requirements.txt
          python manage.py migrate
          python manage.py collectstatic --noinput
          touch /home/dipendr5/django_project/tmp/restart.txt
          EOF
