name: Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Deploy to cPanel
        env:
          CPANEL_USER: dipendr5  # Replace with your cPanel username
          CPANEL_HOST: dipendratamang.com.np  # Replace with your cPanel host/domain/IP
          CPANEL_PORT: 22  # Replace with your cPanel SSH port
        run: |
          ssh-keyscan -H $CPANEL_HOST >> ~/.ssh/known_hosts
          ssh $CPANEL_USER@$CPANEL_HOST -p $CPANEL_PORT << 'EOF'
          source /home/dipendr5/virtualenv/djangopersonalsite/3.8/bin/activate 
          cd /home/dipendr5/djangopersonalsite
          git pull origin master
          pip install -r requirements.txt
          python manage.py migrate
          EOF
