name: Deploy to cPanel

on:
  push:
    branches:
      - master  # Adjust to your default branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Replace with your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to cPanel
        run: |
          ssh dipendr5@python.dipendratamang.com.np 'source /home/dipendr5/virtualenv/python.dipendratamang.com.np/djangopersonalsite/3.8/bin/activate && cd /home/dipendr5/python.dipendratamang.com.np/djangopersonalsite && git pull origin master && pip install -r requirements.txt && python manage.py migrate'
