name: Deploy to cPanel

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          
      - name: Prepare SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DIPENDRA }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $CPANEL_HOST >> ~/.ssh/known_hosts

      - name: Deploy to cPanel
        env:
          CPANEL_USER: dipendr5  # Replace with your cPanel username
          CPANEL_HOST: dipendratamang.com.np  # Replace with your cPanel host/domain/IP
          CPANEL_PORT: 22  # Replace with your cPanel SSH port
        run: |
          ssh -i ~/.ssh/id_rsa $CPANEL_USER@$CPANEL_HOST -p $CPANEL_PORT << 'EOF'
          source /home/dipendr5/virtualenv/djangopersonalsite/3.8/bin/activate
          cd /home/dipendr5/djangopersonalsite
          git pull origin master
          pip install -r requirements.txt
          python manage.py migrate
          python manage.py collectstatic --noinput
          EOF
